theme = "nofancy"
baseURL = "http://corybrunson.github.io/"
languageCode = "en-us"
title = "murmuring in the background"
rssLimit = 6

[permalinks]
  post = "/:year/:month/:day/:slug/"

[params]
  highlight = "github"
  topmenu = "categories"

[author]
  name = "Cory Brunson"
  orcid = "0000-0003-3126-9494"
  publons = "1676577"
  googlescholar = "jcv_PIkAAAAJ"
  github = "corybrunson"
  linkedin = "jasoncorybrunson"
  twitter = "cornelioid"
  goodreads = "57466005"
  
ignoreFiles = [ "\\.[Rr]md$", "\\.[Rr]markdown$", "_files$", "_cache$" ]
